@startuml
left to right direction
actor 出店者
actor 消費者
rectangle ショッピングサイト{
	出店者 --> (起動)
	出店者 --> (ログイン)
	出店者 --> (商品管理)
	出店者 --> (商品検索)
	出店者 --> (ページ作成)
	出店者 --> (ページ閲覧)
	出店者 --> (ページ削除)
	出店者 --> (注文の確認)
	出店者 --> (代金の振り込み案内)
	出店者 --> (金額変更)
	(起動) <-- 消費者
	(ログイン) <-- 消費者
	(商品検索) <-- 消費者
	(ページ閲覧) <-- 消費者
	(商品購入) <-- 消費者
	(商品保存) <-- 消費者
	(問い合わせ) <-- 消費者
	(購入取り消し) <-- 消費者
}
	出店者 --> (商品発送)
	(値下げ)<-- 消費者
	(代引き支払い) <-- 消費者
	(店頭受け取り) <-- 消費者
@enduml